remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: Cruise-AI Docs
description: Hosts travel plans for various cruises, including information about the ship, excursions, and other relevant details.
